### ISSUE TITLE
Can't import body torso

### ISSUE THREAD

**Issue by OldGuy111** [TobyLobster/ImportLDraw#88]
Python crashes at importing torso in version 3.6.4. Will try version 3.5, however test model works fine.
Log
`
Python: Traceback (most recent call last):
  File "C:\Users\MCOldie Spaced\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_importldraw\importldraw.py", line 399, in execute
    loadldraw.loadFromFile(self, self.filepath)
  File "C:\Users\MCOldie Spaced\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_importldraw\loadldraw\loadldraw.py", line 4608, in loadFromFile
    setupInstructionsLook()
  File "C:\Users\MCOldie Spaced\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_importldraw\loadldraw\loadldraw.py", line 4128, in setupInstructionsLook
    setupLineset(solidBlackLineset, 2.25, 'Black Edged Bricks Collection')
  File "C:\Users\MCOldie Spaced\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_importldraw\loadldraw\loadldraw.py", line 3875, in setupLineset
    if 'LegoMaterial' not in lineset.linestyle.color_modifiers:
TypeError: bpy_prop_collection.__contains__: FreestyleLineStyle.color_modifiers does not support string lookups`

**Comment by OldGuy111** [comment]
Just noticed Blender 2.8.1 is the version designated.
