### ISSUE TITLE
Compatiblity problems with Blender 4.0

### ISSUE THREAD

**Issue by shugosmail** [TobyLobster/ImportLDraw#89]
Hi, 

I tried importldraw 1.1.18 plugin in the current beta version of Blender 4.0 ( Stable 4.0 will be released on November 14th ). Blender 4.0 have some **breaking python changes:** There were also some bevel changes mades which are not compatible anymore.
[https://wiki.blender.org/wiki/Reference/Release_Notes/4.0/Python_API#Breaking_changes](url)

Could you, please, look at it?

**LOG example:**
reloading addon: io_scene_importldraw 1699375448.8888137 1699376021.991847 'C:\\Users\\shugo\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons\\io_scene_importldraw\\__init__.py'
Modules Installed () from 'D:\\Blender Versions\\Blender Plugins\\importldraw1.1.18_for_blender_281.zip' into 'C:\\Users\\shugo\\AppData\\Roaming\\Blender Foundation\\Blender\\4.0\\scripts\\addons'
addon_utils.disable: io_scene_importldraw not disabled
Traceback (most recent call last):
  File "D:\Blender Versions\blender-4.0.0-beta+v40.abe925d0c671-windows.amd64-release\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "D:\Blender Versions\blender-4.0.0-beta+v40.abe925d0c671-windows.amd64-release\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\shugo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_importldraw\__init__.py", line 22, in <module>
    from . import importldraw
  File "C:\Users\shugo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_importldraw\importldraw.py", line 38, in <module>
    from .loadldraw import loadldraw
  File "C:\Users\shugo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_importldraw\loadldraw\loadldraw.py", line 1673, in <module>
    class BlenderMaterials:
  File "C:\Users\shugo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_importldraw\loadldraw\loadldraw.py", line 1677, in BlenderMaterials
    __hasPrincipledShader = "ShaderNodeBsdfPrincipled" in [node.nodetype for node in getattr(bpy.types, "NODE_MT_category_SH_NEW_SHADER").category.items(None)]
AttributeError: 'module' object has no attribute 'NODE_MT_category_SH_NEW_SHADER'

**Comment by cjhendrix** [comment]
Just to add that I'm getting the same error.

**Comment by ramonhollands** [comment]
Same here

**Comment by JoshCodeStuff** [comment]
same error for me as well.

**Comment by Telemattic** [comment]
Yes, same error here

**Comment by barclay99x** [comment]
Same here

![image](https://github.com/TobyLobster/ImportLDraw/assets/52984812/b8011023-ffb0-4ce3-a516-f1c8743f1eb5)

**Comment by Keksstar** [comment]
@TobyLobster Hi Toby, do you had the chance to look into this one?

**Comment by zachstronaut** [comment]
Hey, if you're arriving here cause you just want to play with BrickLink Studio creations in Blender with this importer, there may be no reason for you to use Blender 4. Try the LTS (Long Term Support) stable version of Blender:

https://www.blender.org/download/lts/

**Comment by TobyLobster** [comment]
By popular demand, the latest release has Blender 4 support now. Enjoy!

**Comment by shugosmail** [comment]
Thank you very much, I've tested it and everything works perfectly.

**Comment by cjhendrix** [comment]
Thanks so much for the update and this project in general! It's become an important part of my workflow.
