### ISSUE TITLE
Update to Blender 4.2

### ISSUE THREAD

**Issue by DanyaKreyg** [TobyLobster/ImportLDraw#94]
Hi!
I absolutely love your extension.
Would it be possible for you to update the plugin so that it could work together with blender 4.2?
Would mean a world to me.
Here is the Log I get when I try add the plugin into Blender 4.2 if that can help you

`Report: Error

Traceback (most recent call last):
  File "C:\Users\Stimpy\AppData\Local\ovpkg\blender-4.2.0-usd.02.0\Release\4.2\scripts\modules\addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
  File "C:\Users\Stimpy\AppData\Local\ovpkg\blender-4.2.0-usd.02.0\Release\4.2\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Stimpy\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_importldraw\__init__.py", line 22, in <module>
    from . import importldraw
  File "C:\Users\Stimpy\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_importldraw\importldraw.py", line 38, in <module>
    from .loadldraw import loadldraw
  File "C:\Users\Stimpy\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_importldraw\loadldraw\loadldraw.py", line 1714, in <module>
    class BlenderMaterials:
  File "C:\Users\Stimpy\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_importldraw\loadldraw\loadldraw.py", line 1718, in BlenderMaterials
    _hasPrincipledShader = "ShaderNodeBsdfPrincipled" in [node.identifier for node in getattr(bpy.types, "NODE_MT_category_SH_NEW_SHADER").category.items(None)]
AttributeError: 'module' object has no attribute 'NODE_MT_category_SH_NEW_SHADER'`

**Comment by sampotter123** [comment]
fyi there's a different importer which is constantly updated

https://github.com/cuddlyogre/ExportLDraw

**Comment by TobyLobster** [comment]
The latest version of the extension appears to work for me in Blender 4.2.0 fine. Check you have the latest version of the importer. Your error output suggests you have an earlier version.
